## Numpy Array and Basics

In [5]:
import numpy as np
import time 

### Creating array from list

In [6]:
arr_1d = np.array([1, 2, 3])
print(f"1D array------\n{arr_1d}")

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(f"2D array------\n{arr_2d}")

arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(f"3D array------\n{arr_3d}")

1D array------
[1 2 3]
2D array------
[[1 2 3]
 [4 5 6]]
3D array------
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### list vs numpy array

In [7]:
py_list = [1, 2, 4, 6, 8]
print(f"Puthon List Multiplied by 2------\n{py_list * 2}")

np_array = np.array([1, 2, 4, 6, 8])    # Element Wise Multiplication
print(f"NumPy Array Multiplied by 2------\n{np_array * 2}")

Puthon List Multiplied by 2------
[1, 2, 4, 6, 8, 1, 2, 4, 6, 8]
NumPy Array Multiplied by 2------
[ 2  4  8 12 16]


#### Know the time to process this 



In [10]:
start = time.time()
py_list = [i*2 for i in range(1000000)]
print(f"\n List operation time = {time.time() - start}")

start = time.time()
np_array = np.arange(1000000) * 2
print(f"\n NumPy Array operation time = {time.time() - start}")


 List operation time = 0.05513501167297363

 NumPy Array operation time = 0.003007173538208008


### Creating Array from Scratch 

In [17]:
zeros = np.zeros((3, 3))
print(f"zeros array------\n{zeros}")

ones = np.ones((3, 3))
print(f"ones array------\n{ones}")

full = np.full((3, 3), 5)
print(f"full array------\n{full}")

random = np.random.random((3, 3))
print(f"random array------\n{random}")

sequence = np.arange(0, 11, 2)
print(f"sequence array------\n{sequence}")


zeros array------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ones array------
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
full array------
[[5 5 5]
 [5 5 5]
 [5 5 5]]
random array------
[[0.93074277 0.74088945 0.07626134]
 [0.92006615 0.85788449 0.42391741]
 [0.97846639 0.22642138 0.76457516]]
sequence array------
[ 0  2  4  6  8 10]


### Vector, Matrix & Tensor  

In [20]:
vector = np.array([1, 2, 3])
print(f"Vector: {vector}")

matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print(f"Matrix: \n{matrix}")

tensor = np.array([[[1, 2],
                    [3, 4],
                    [4, 5]]])
print(f"Tensors: \n{tensor}")

Vector: [1 2 3]
Matrix: 
[[1 2 3]
 [4 5 6]]
Tensors: 
[[[1 2]
  [3 4]
  [4 5]]]


## Array Properties

In [22]:
arr = np.array([[1, 2, 3],
                [5, 6, 7]])
print("Shape of array: ", arr.shape)
print("Dimension of array: ", arr.ndim)
print("Size of array: ", arr.size)
print("Data type of array: ", arr.dtype)

Shape of array:  (2, 3)
Dimension of array:  2
Size of array:  6
Data type of array:  int64


#### Array Reshaping


In [ ]:
arr = np.arange(12)
print(f"Original array ",arr)

reshape_arr = arr.reshape((3, 4))
