In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
# creating np array in different values 
array1 = np.array([[1, 3, 4], [6, 2, 9]])
array2 = np.random.rand(3, 3)
array3 = np.zeros((4, 4))

In [10]:
# save np array in npy format
np.save('data/array1.npy', array1)
np.save("data/array2.npy", array2)
np.save("data/array3.npy", array3)

In [12]:
# load the files in the np
loaded_array1 = np.load("data/array1.npy")
print(loaded_array1)

loaded_array2 = np.load("data/array2.npy")
print(loaded_array2)

[[1 3 4]
 [6 2 9]]
[[0.33863958 0.89542468 0.56192272]
 [0.41722352 0.45653293 0.67080765]
 [0.60697168 0.69927961 0.52849788]]


In [ ]:
# operation with pictures