## NumPy Array Operations

In [8]:
import numpy as np
import time 

In [4]:
# Slicing in np array 
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])
print(f"Basic Slicing: {arr[1:9]}")
print(f"With Step: {arr[1:9:6]}")
print(f"Negative indexing: {arr[-2]}")


Basic Slicing: [2 3 4 5 6 7 8 9]
With Step: [2 8]
Negative indexing: 10


In [10]:
# Slicing in np 2d array 
# print Specific element in python:
arr_2d = np.array([[1, 2, 3],
                   [5, 6, 8],
                   [6, 5, 2]]) 
print("Specific element", arr_2d[1, 1])
print("Entire Row:", arr_2d[1])
print("ENtire Column", arr_2d[:, 0]) 

Specific element 6
Entire Row: [5 6 8]
ENtire Collum [1 5 6]


### Array Sorting---------

In [12]:
unsorted_arr = np.array([7, 5, 4, 6, 33, 5, 3, 5, 77, 88, 85, 2, 1, 3])
print("Sorted array", np.sort(unsorted_arr))
unsorted_arr_2d = np.array([[1, 2, 3],
                   [5, 6, 8],
                   [6, 5, 2]]) 
print("Sorted 2D array by column", np.sort(unsorted_arr_2d, axis=1)) 

Sorted array [ 1  2  3  3  4  5  5  5  6  7 33 77 85 88]
Sorted 2D array by column [[1 2 3]
 [5 6 8]
 [2 5 6]]


### Array Filter---------

In [9]:
numbers = np.array([1, 3, 4, 2, 5, 6, 7, 8, 9, 3, 5])
even_num = numbers[numbers % 2 == 0]
print(f"Even Np array: {even_num}")

Even Np array: [4 2 6 8]


### Filter with mask--------

In [10]:
mask = numbers > 5
print("Numbers Grater than 5", numbers[mask])

Numbers Grater than 5 [6 7 8 9]


### Fancy indexing vs np.where()-------

In [11]:
# index number for the np array value 
indeces = [6, 8, 4, 2, 1]
# print the value using index numbers 
print(numbers[indeces])

# using where mask the np array
where_result = np.where(numbers > 5)
print(where_result)
print("NP where", numbers[where_result]) 

[7 9 5 4 3]
(array([5, 6, 7, 8]),)
NP where [6 7 8 9]


In [ ]:
# condition Np where array 
condition_array = np.where(numbers > 5, 'true', 'false')
print(condition_array)

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'false' 'false']


## Adding and Removing Data in NP array

In [43]:
# Marge Array's 
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

# adding 2 array's 
add_array = arr1 + arr2
print(f"array1 + array2 = {add_array}")

# combine two array's 
combined = np.concatenate((arr1, arr2))
print("Combine / concatinate two array =", combined)

array1 + array2 = [ 7  9 11 13 15]
Combine / concatinate two array = [ 1  2  3  4  5  6  7  8  9 10]
