## Advance Operation with Business Examles

In [3]:
import numpy as np
import matplotlib.pyplot as plt

In [8]:
# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000], # Paradise Biryani
    [2, 120000, 140000, 160000, 190000], # Beijing Bites
    [3, 200000, 230000, 260000, 300000], # Pizza Hub
    [4, 180000, 210000, 240000, 270000], # Burger Point
    [5, 160000, 185000, 205000, 230000]# Chai Point
])

print(" ==== Zomato sales analysys ==== \n")
# print shape of the np array
print("Shape of the array: \n",sales_data.shape)
# print 1st 3 data of the elements
print(f"Sample Data for 1st 3 restau:\n{sales_data[:3]}")


 ==== Zomato sales analysys ==== 

Shape of the array: 
 (5, 5)
Sample Data for 1st 3 restau:
[[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]


In [17]:
# print total sales of the year 
# method 0
print(np.sum(sales_data, axis = 0))
# method 1 
sale_yearly_sale = np.sum(sales_data[:, 1:], axis = 0)
print(sale_yearly_sale)

# total sum of the last 5 year 
print(f"The last 5 year total sales----\n{np.sum(sale_yearly_sale)}")

[     15  810000  945000 1085000 1240000]
[ 810000  945000 1085000 1240000]
The last 5 year total sales----
4080000
